
import { ShiftType, ShiftVariable, CalendarTheme } from './types';

export const DEFAULT_SHIFT_TYPES: ShiftType[] = [
  { id: 't1', name: 'NORMAL', dailyRate: 0, color: 'bg-blue-100 text-blue-800' },
  { id: 't2', name: 'IDA', dailyRate: 0, color: 'bg-orange-100 text-orange-800' },
  { id: 't3', name: 'VUELTA', dailyRate: 0, color: 'bg-green-100 text-green-800' },
  { id: 't4', name: 'IDA/VUELTA', dailyRate: 0, color: 'bg-purple-100 text-purple-800' },
  { id: 't5', name: 'LIBRE', dailyRate: 0, color: 'bg-emerald-100 text-emerald-800' },
  { id: 't6', name: 'RESERVA', dailyRate: 0, color: 'bg-amber-100 text-amber-800' },
  { id: 't7', name: 'FORMACIÓN', dailyRate: 0, color: 'bg-cyan-100 text-cyan-800' },
  { id: 't8', name: 'VACACIONES', dailyRate: 0, color: 'bg-rose-100 text-rose-800' },
];

export const DEFAULT_VARIABLES: ShiftVariable[] = [
  { id: 'v_sun', name: 'DOMINGO', type: 'fixed', amount: 92.25 },
  { id: 'v_fest', name: 'FESTIVO', type: 'fixed', amount: 92.25 },
  { id: 'v_exc', name: 'EXCESOS', type: 'fixed', amount: 0 },
  { id: 'v_tl1', name: 'TURNO LARGO 1', type: 'fixed', amount: 19.48 },
  { id: 'v_tl2', name: 'TURNO LARGO 2', type: 'fixed', amount: 25.63 },
  { id: 'v_tdl', name: 'TRABAJO DIA LIBRE', type: 'fixed', amount: 205 },
  { id: 'v_pi', name: 'PLUS INCIDENCIA', type: 'fixed', amount: 100 },
  { id: 'v_dcp', name: 'DIETA CON PERNOCTA', type: 'fixed', amount: 26 },
  { id: 'v_dsp', name: 'DIETA SIN PERNOCTA', type: 'fixed', amount: 15 },
  { id: 'v_de', name: 'DIAS ESPECIAL', type: 'fixed', amount: 0 },
];

export const CALENDAR_THEMES: CalendarTheme[] = [
  {
    id: 'minimal',
    name: 'Blanco',
    bg: 'bg-white',
    border: 'border-gray-200',
    headerBg: 'bg-gray-50/50',
    headerText: 'text-gray-800',
    accentText: 'text-gray-400',
    dayNameText: 'text-gray-400',
    emptyCell: 'bg-gray-50/50',
    cellBg: 'bg-white',
    cellBorder: 'border-gray-100',
    cellText: 'text-gray-700',
    cellHover: 'hover:border-gray-400',
    sundayBg: 'bg-gray-50',
    sundayText: 'text-gray-900',
    todayBg: 'bg-indigo-50',
    todayBorder: 'border-indigo-500',
    todayText: 'text-indigo-600',
    plusBtn: 'bg-gray-800 hover:bg-black'
  },
  {
    id: 'sky',
    name: 'Cielo',
    bg: 'bg-sky-50',
    border: 'border-sky-100',
    headerBg: 'bg-white/80',
    headerText: 'text-slate-800',
    accentText: 'text-sky-600',
    dayNameText: 'text-sky-400',
    emptyCell: 'bg-sky-100/30',
    cellBg: 'bg-white',
    cellBorder: 'border-sky-100',
    cellText: 'text-slate-700',
    cellHover: 'hover:border-sky-400',
    sundayBg: 'bg-sky-100/80',
    sundayText: 'text-sky-900',
    todayBg: 'bg-indigo-50',
    todayBorder: 'border-indigo-400',
    todayText: 'text-indigo-600',
    plusBtn: 'bg-sky-500 hover:bg-sky-600'
  },
  {
    id: 'navy',
    name: 'Marino',
    bg: 'bg-[#0f172a]',
    border: 'border-blue-900/50',
    headerBg: 'bg-blue-900/20',
    headerText: 'text-white',
    accentText: 'text-blue-400',
    dayNameText: 'text-blue-400/70',
    emptyCell: 'bg-blue-900/10',
    cellBg: 'bg-blue-900/30',
    cellBorder: 'border-blue-800/50',
    cellText: 'text-slate-300',
    cellHover: 'hover:border-blue-500',
    sundayBg: 'bg-blue-800/20',
    sundayText: 'text-blue-100',
    todayBg: 'bg-indigo-600/40',
    todayBorder: 'border-indigo-400',
    todayText: 'text-white',
    plusBtn: 'bg-blue-700/50 hover:bg-blue-500'
  },
  {
    id: 'emerald',
    name: 'Selva',
    bg: 'bg-emerald-50',
    border: 'border-emerald-100',
    headerBg: 'bg-white/80',
    headerText: 'text-emerald-900',
    accentText: 'text-emerald-600',
    dayNameText: 'text-emerald-400',
    emptyCell: 'bg-emerald-100/30',
    cellBg: 'bg-white',
    cellBorder: 'border-emerald-100',
    cellText: 'text-emerald-800',
    cellHover: 'hover:border-emerald-400',
    sundayBg: 'bg-emerald-100/80',
    sundayText: 'text-emerald-900',
    todayBg: 'bg-teal-50',
    todayBorder: 'border-teal-500',
    todayText: 'text-teal-700',
    plusBtn: 'bg-emerald-600 hover:bg-emerald-700'
  },
  {
    id: 'custom',
    name: 'Personal',
    bg: '',
    border: '',
    headerBg: '',
    headerText: '',
    accentText: '',
    dayNameText: '',
    emptyCell: '',
    cellBg: '',
    cellBorder: '',
    cellText: '',
    cellHover: '',
    sundayBg: '',
    sundayText: '',
    todayBg: '',
    todayBorder: '',
    todayText: '',
    plusBtn: ''
  }
];

export const STORAGE_KEY = 'shiftcash_data_v12';
